/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrademarkSearchRouteImport } from './routes/trademark-search'
import { Route as GlobalTrademarkRouteImport } from './routes/global-trademark'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackApplicationIdRouteImport } from './routes/track.$applicationId'
import { Route as ServicesPatentsRouteImport } from './routes/services.patents'
import { Route as ServicesIprRouteImport } from './routes/services.ipr'
import { Route as ServicesDesignsRouteImport } from './routes/services.designs'
import { Route as ServicesCopyrightsRouteImport } from './routes/services.copyrights'

const TrademarkSearchRoute = TrademarkSearchRouteImport.update({
  id: '/trademark-search',
  path: '/trademark-search',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalTrademarkRoute = GlobalTrademarkRouteImport.update({
  id: '/global-trademark',
  path: '/global-trademark',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackApplicationIdRoute = TrackApplicationIdRouteImport.update({
  id: '/track/$applicationId',
  path: '/track/$applicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPatentsRoute = ServicesPatentsRouteImport.update({
  id: '/services/patents',
  path: '/services/patents',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIprRoute = ServicesIprRouteImport.update({
  id: '/services/ipr',
  path: '/services/ipr',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDesignsRoute = ServicesDesignsRouteImport.update({
  id: '/services/designs',
  path: '/services/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCopyrightsRoute = ServicesCopyrightsRouteImport.update({
  id: '/services/copyrights',
  path: '/services/copyrights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRoute
  '/global-trademark': typeof GlobalTrademarkRoute
  '/trademark-search': typeof TrademarkSearchRoute
  '/services/copyrights': typeof ServicesCopyrightsRoute
  '/services/designs': typeof ServicesDesignsRoute
  '/services/ipr': typeof ServicesIprRoute
  '/services/patents': typeof ServicesPatentsRoute
  '/track/$applicationId': typeof TrackApplicationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRoute
  '/global-trademark': typeof GlobalTrademarkRoute
  '/trademark-search': typeof TrademarkSearchRoute
  '/services/copyrights': typeof ServicesCopyrightsRoute
  '/services/designs': typeof ServicesDesignsRoute
  '/services/ipr': typeof ServicesIprRoute
  '/services/patents': typeof ServicesPatentsRoute
  '/track/$applicationId': typeof TrackApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRoute
  '/global-trademark': typeof GlobalTrademarkRoute
  '/trademark-search': typeof TrademarkSearchRoute
  '/services/copyrights': typeof ServicesCopyrightsRoute
  '/services/designs': typeof ServicesDesignsRoute
  '/services/ipr': typeof ServicesIprRoute
  '/services/patents': typeof ServicesPatentsRoute
  '/track/$applicationId': typeof TrackApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/global-trademark'
    | '/trademark-search'
    | '/services/copyrights'
    | '/services/designs'
    | '/services/ipr'
    | '/services/patents'
    | '/track/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/global-trademark'
    | '/trademark-search'
    | '/services/copyrights'
    | '/services/designs'
    | '/services/ipr'
    | '/services/patents'
    | '/track/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/global-trademark'
    | '/trademark-search'
    | '/services/copyrights'
    | '/services/designs'
    | '/services/ipr'
    | '/services/patents'
    | '/track/$applicationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  DashboardRoute: typeof DashboardRoute
  GlobalTrademarkRoute: typeof GlobalTrademarkRoute
  TrademarkSearchRoute: typeof TrademarkSearchRoute
  ServicesCopyrightsRoute: typeof ServicesCopyrightsRoute
  ServicesDesignsRoute: typeof ServicesDesignsRoute
  ServicesIprRoute: typeof ServicesIprRoute
  ServicesPatentsRoute: typeof ServicesPatentsRoute
  TrackApplicationIdRoute: typeof TrackApplicationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trademark-search': {
      id: '/trademark-search'
      path: '/trademark-search'
      fullPath: '/trademark-search'
      preLoaderRoute: typeof TrademarkSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-trademark': {
      id: '/global-trademark'
      path: '/global-trademark'
      fullPath: '/global-trademark'
      preLoaderRoute: typeof GlobalTrademarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$applicationId': {
      id: '/track/$applicationId'
      path: '/track/$applicationId'
      fullPath: '/track/$applicationId'
      preLoaderRoute: typeof TrackApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/patents': {
      id: '/services/patents'
      path: '/services/patents'
      fullPath: '/services/patents'
      preLoaderRoute: typeof ServicesPatentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ipr': {
      id: '/services/ipr'
      path: '/services/ipr'
      fullPath: '/services/ipr'
      preLoaderRoute: typeof ServicesIprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/designs': {
      id: '/services/designs'
      path: '/services/designs'
      fullPath: '/services/designs'
      preLoaderRoute: typeof ServicesDesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/copyrights': {
      id: '/services/copyrights'
      path: '/services/copyrights'
      fullPath: '/services/copyrights'
      preLoaderRoute: typeof ServicesCopyrightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  DashboardRoute: DashboardRoute,
  GlobalTrademarkRoute: GlobalTrademarkRoute,
  TrademarkSearchRoute: TrademarkSearchRoute,
  ServicesCopyrightsRoute: ServicesCopyrightsRoute,
  ServicesDesignsRoute: ServicesDesignsRoute,
  ServicesIprRoute: ServicesIprRoute,
  ServicesPatentsRoute: ServicesPatentsRoute,
  TrackApplicationIdRoute: TrackApplicationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
