/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrademarkSearchRouteImport } from './routes/trademark-search'
import { Route as IndexRouteImport } from './routes/index'

const TrademarkSearchRoute = TrademarkSearchRouteImport.update({
  id: '/trademark-search',
  path: '/trademark-search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trademark-search': typeof TrademarkSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trademark-search': typeof TrademarkSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trademark-search': typeof TrademarkSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trademark-search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trademark-search'
  id: '__root__' | '/' | '/trademark-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrademarkSearchRoute: typeof TrademarkSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trademark-search': {
      id: '/trademark-search'
      path: '/trademark-search'
      fullPath: '/trademark-search'
      preLoaderRoute: typeof TrademarkSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrademarkSearchRoute: TrademarkSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
